name: expense_manager_server
description: Server for expense manager Flutter web app

environment:
  sdk: ^3.8.0

dependencies:
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^5.0.0